# Generated by Django 4.2.11 on 2024-06-21 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_sharing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='cooking_instructions',
        ),
    ]
