# Generated by Django 4.2.11 on 2024-06-21 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_sharing', '0002_remove_recipe_cooking_instructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/profile_images'),
        ),
    ]
