# Generated by Django 4.2.11 on 2024-06-21 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_sharing', '0004_remove_recipe_servings_remove_userprofile_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.CharField(max_length=300),
        ),
    ]
